# Generated by Django 4.1.5 on 2023-02-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('date', models.CharField(max_length=12)),
                ('base_type', models.CharField(max_length=13)),
                ('type', models.CharField(max_length=3)),
                ('gender', models.CharField(max_length=6)),
                ('match_id', models.IntegerField(primary_key=True, serialize=False)),
                ('teams', models.CharField(max_length=128)),
            ],
        ),
    ]
